name: Docker Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Clone, Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Clone
        uses: actions/checkout@v2

      # Create a temporary .env.production.local file and write all the environment variables
      # needed to build from Github secrets
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: './'
          file: '.env.production.local'
          content: |
            NEXT_PUBLIC_TYPEDDATADOMAIN_NAME=${{ secrets.NEXT_PUBLIC_TYPEDDATADOMAIN_NAME }}
            NEXT_PUBLIC_TYPEDDATADOMAIN_VERSION=${{ secrets.NEXT_PUBLIC_TYPEDDATADOMAIN_VERSION }}
            NEXT_PUBLIC_TYPEDDATADOMAIN_CHAINID=${{ secrets.NEXT_PUBLIC_TYPEDDATADOMAIN_CHAINID }}
            NEXT_PUBLIC_TYPEDDATADOMAIN_VOUCHER_CONTRACT=${{ secrets.NEXT_PUBLIC_TYPEDDATADOMAIN_VOUCHER_CONTRACT }}

      - name: Build and publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          repository: ledgerhq/innovation-voucher-web
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: v1.0.4
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs') }}
