name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Clone, Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build and publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          repository: ledgerhq/innovation-voucher-web
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: v1.0.0
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs') }}